apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes: 
    - ReadWriteMany
  hostPath:
    path: /home/kubeadmin/Documents/workspace/kubernetes-projects/volumes/story-app/data
    type: DirectoryOrCreate
