apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  labels:
    app: fastapi
    type: frontend
spec:
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
        type: frontend
    spec:
      containers:
      - name: fastapi-container
        image: rageshn/fastapi-image
  replicas: 1